### ISSUE TITLE
more mob engines to use

### ISSUE THREAD

**Issue by 22i** [AntumMT/mod-unimobiles#1]
open ai https://forum.minetest.net/viewtopic.php?f=9&t=16032
animals modpack https://forum.minetest.net/viewtopic.php?t=629
mila https://forum.minetest.net/viewtopic.php?f=9&t=15375
nodebox mob api https://forum.minetest.net/viewtopic.php?t=16557
sofar entity ai https://forum.minetest.net/viewtopic.php?t=15572

**Comment by AntumDeluge** [comment]
@22i Thank you, I will look into those.
